app:
    resource: "../src/AppBundle/Controller/"
    type:     annotation

admin:
    resource: "../src/AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

logout:
    path: /logout